In [21]:
import pandas as pd
data=pd.read_csv('dataset.csv',low_memory=False)
data.shape

(958524, 45)

In [22]:
data.head(5)

,id,spkid,full_name,pdes,name,prefix,neo,pha,H,diameter,...,sigma_i,sigma_om,sigma_w,sigma_ma,sigma_ad,sigma_n,sigma_tp,sigma_per,class,rms
0,a0000001,2000001,1 Ceres,1,Ceres,NaN,N,N,3.40,939.400,...,4.608900e-09,6.168800e-08,6.624800e-08,7.820700e-09,1.111300e-11,1.196500e-12,3.782900e-08,9.415900e-09,MBA,0.43301
1,a0000002,2000002,2 Pallas,2,Pallas,NaN,N,N,4.20,545.000,...,3.469400e-06,6.272400e-06,9.128200e-06,8.859100e-06,4.961300e-09,4.653600e-10,4.078700e-05,3.680700e-06,MBA,0.35936
2,a0000003,2000003,3 Juno,3,Juno,NaN,N,N,5.33,246.596,...,3.223100e-06,1.664600e-05,1.772100e-05,8.110400e-06,4.363900e-09,4.413400e-10,3.528800e-05,3.107200e-06,MBA,0.33848
3,a0000004,2000004,4 Vesta,4,Vesta,NaN,N,N,3.00,525.400,...,2.170600e-07,3.880800e-07,1.789300e-07,1.206800e-06,1.648600e-09,2.612500e-10,4.103700e-06,1.274900e-06,MBA,0.39980
4,a0000005,2000005,5 Astraea,5,Astraea,NaN,N,N,6.90,106.699,...,2.740800e-06,2.894900e-05,2.984200e-05,8.303800e-06,4.729000e-09,5.522700e-10,3.474300e-05,3.490500e-06,MBA,0.52191

In [23]:
data.columns

Index(['id', 'spkid', 'full_name', 'pdes', 'name', 'prefix', 'neo', 'pha', 'H',
       'diameter', 'albedo', 'diameter_sigma', 'orbit_id', 'epoch',
       'epoch_mjd', 'epoch_cal', 'equinox', 'e', 'a', 'q', 'i', 'om', 'w',
       'ma', 'ad', 'n', 'tp', 'tp_cal', 'per', 'per_y', 'moid', 'moid_ld',
       'sigma_e', 'sigma_a', 'sigma_q', 'sigma_i', 'sigma_om', 'sigma_w',
       'sigma_ma', 'sigma_ad', 'sigma_n', 'sigma_tp', 'sigma_per', 'class',
       'rms'],
      dtype='str')

In [24]:
data.drop(
    [
        'id', 'spkid', 'full_name', 'pdes', 'name', 'prefix',
        'orbit_id', 'equinox', 'epoch', 'epoch_mjd', 'epoch_cal',
        'tp', 'tp_cal', 'sigma_e', 'sigma_a', 'sigma_q',
        'sigma_i', 'sigma_om', 'sigma_w', 'sigma_ma',
        'sigma_ad', 'sigma_n', 'sigma_tp', 'sigma_per', 'rms'
    ],axis=1,inplace=True
)

In [25]:
data.head(5)

,neo,pha,H,diameter,albedo,diameter_sigma,e,a,q,i,om,w,ma,ad,n,per,per_y,moid,moid_ld,class
0,N,N,3.40,939.400,0.0900,0.200,0.076009,2.769165,2.558684,10.594067,80.305531,73.597695,77.372098,2.979647,0.213885,1683.145703,4.608202,1.59478,620.640533,MBA
1,N,N,4.20,545.000,0.1010,18.000,0.229972,2.773841,2.135935,34.832932,173.024741,310.202392,144.975675,3.411748,0.213345,1687.410992,4.619880,1.23429,480.348639,MBA
2,N,N,5.33,246.596,0.2140,10.594,0.256936,2.668285,1.982706,12.991043,169.851482,248.066193,125.435355,3.353865,0.226129,1592.013769,4.358696,1.03429,402.514639,MBA
3,N,N,3.00,525.400,0.4228,0.200,0.088721,2.361418,2.151909,7.141771,103.810804,150.728541,95.861938,2.570926,0.271609,1325.432763,3.628837,1.13948,443.451432,MBA
4,N,N,6.90,106.699,0.2740,3.140,0.190913,2.574037,2.082619,5.367427,141.571026,358.648418,17.846343,3.065455,0.238661,1508.414421,4.129814,1.09575,426.433027,MBA

In [26]:
data.drop(['diameter_sigma','moid_ld'],axis=1,inplace=True)

In [27]:
data.head(5)

,neo,pha,H,diameter,albedo,e,a,q,i,om,w,ma,ad,n,per,per_y,moid,class
0,N,N,3.40,939.400,0.0900,0.076009,2.769165,2.558684,10.594067,80.305531,73.597695,77.372098,2.979647,0.213885,1683.145703,4.608202,1.59478,MBA
1,N,N,4.20,545.000,0.1010,0.229972,2.773841,2.135935,34.832932,173.024741,310.202392,144.975675,3.411748,0.213345,1687.410992,4.619880,1.23429,MBA
2,N,N,5.33,246.596,0.2140,0.256936,2.668285,1.982706,12.991043,169.851482,248.066193,125.435355,3.353865,0.226129,1592.013769,4.358696,1.03429,MBA
3,N,N,3.00,525.400,0.4228,0.088721,2.361418,2.151909,7.141771,103.810804,150.728541,95.861938,2.570926,0.271609,1325.432763,3.628837,1.13948,MBA
4,N,N,6.90,106.699,0.2740,0.190913,2.574037,2.082619,5.367427,141.571026,358.648418,17.846343,3.065455,0.238661,1508.414421,4.129814,1.09575,MBA

In [28]:
data.isnull().sum()

neo              4
pha          19921
H             6263
diameter    822315
albedo      823421
e                0
a                0
q                0
i                0
om               0
w                0
ma               1
ad               4
n                0
per              4
per_y            1
moid         19921
class            0
dtype: int64

In [29]:
# TASK 1: PHA CLASSIFICATION
# ================================
df_pha = data.drop(columns=['moid', 'diameter', 'albedo'], errors='ignore')

df_pha['neo'] = df_pha['neo'].fillna(df_pha['neo'].mode()[0])
df_pha = df_pha.dropna(subset=['pha'])
df_pha['H'] = df_pha['H'].fillna(df_pha['H'].median())
df_pha = df_pha.dropna(subset=['ma', 'ad', 'per', 'per_y'])

df_pha['neo'] = df_pha['neo'].map({'N': 0, 'Y': 1})
df_pha['pha'] = df_pha['pha'].map({'N': 0, 'Y': 1})
df_pha = pd.get_dummies(df_pha, columns=['class'], drop_first=True, dtype=int)

df_pha.to_csv('pha_preprocessed.csv', index=False)
print("PHA dataset saved:", df_pha.shape)
print(df_pha.isnull().sum().sum(), "nulls remaining")

PHA dataset saved: (938598, 25)
0 nulls remaining

In [30]:
# TASK 2: DIAMETER REGRESSION
# ================================
df_dia = data.drop(columns=['pha', 'albedo'], errors='ignore')

df_dia['neo'] = df_dia['neo'].fillna(df_dia['neo'].mode()[0])
df_dia = df_dia.dropna(subset=['diameter'])
df_dia['H'] = df_dia['H'].fillna(df_dia['H'].median())
df_dia['moid'] = df_dia['moid'].fillna(df_dia['moid'].median())
df_dia = df_dia.dropna(subset=['ma', 'ad', 'per', 'per_y'])

df_dia['neo'] = df_dia['neo'].map({'N': 0, 'Y': 1})
df_dia = pd.get_dummies(df_dia, columns=['class'], drop_first=True, dtype=int)

df_dia.to_csv('diameter_preprocessed.csv', index=False)
print("Diameter dataset saved:", df_dia.shape)
print(df_dia.isnull().sum().sum(), "nulls remaining")

Diameter dataset saved: (136209, 25)
0 nulls remaining

CLASSIFICATION

In [2]:
#=================================
#1.Logistic Regresssion
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression

In [3]:
df1 = pd.read_csv('pha_preprocessed.csv')
df1.head(5)

,neo,pha,H,e,a,q,i,om,w,ma,...,class_AST,class_ATE,class_CEN,class_IEO,class_IMB,class_MBA,class_MCA,class_OMB,class_TJN,class_TNO
0,0,0,3.40,0.076009,2.769165,2.558684,10.594067,80.305531,73.597695,77.372098,...,0,0,0,0,0,1,0,0,0,0
1,0,0,4.20,0.229972,2.773841,2.135935,34.832932,173.024741,310.202392,144.975675,...,0,0,0,0,0,1,0,0,0,0
2,0,0,5.33,0.256936,2.668285,1.982706,12.991043,169.851482,248.066193,125.435355,...,0,0,0,0,0,1,0,0,0,0
3,0,0,3.00,0.088721,2.361418,2.151909,7.141771,103.810804,150.728541,95.861938,...,0,0,0,0,0,1,0,0,0,0
4,0,0,6.90,0.190913,2.574037,2.082619,5.367427,141.571026,358.648418,17.846343,...,0,0,0,0,0,1,0,0,0,0

In [4]:
df1.isnull().sum()

neo          0
pha          0
H            0
e            0
a            0
q            0
i            0
om           0
w            0
ma           0
ad           0
n            0
per          0
per_y        0
class_APO    0
class_AST    0
class_ATE    0
class_CEN    0
class_IEO    0
class_IMB    0
class_MBA    0
class_MCA    0
class_OMB    0
class_TJN    0
class_TNO    0
dtype: int64

In [5]:
X = df1.drop(columns=['pha'])
y = df1['pha']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled, y_train)
preds = model.predict(X_test_scaled)

In [7]:
acc = accuracy_score(y_test, preds)
print("Logistic Regression Accuracy:", acc)
print(classification_report(y_test, preds, target_names=['Not PHA', 'PHA']))

Logistic Regression Accuracy: 0.9976880460259961
              precision    recall  f1-score   support

     Not PHA       1.00      1.00      1.00    187311
         PHA       0.42      0.15      0.23       409

    accuracy                           1.00    187720
   macro avg       0.71      0.58      0.61    187720
weighted avg       1.00      1.00      1.00    187720

In [8]:
#================================
#2.DecisionTree Classifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

model2 = DecisionTreeClassifier(random_state=42)
model2.fit(X_train, y_train)
preds2 = model2.predict(X_test)

acc2 = accuracy_score(y_test, preds2)
print("Decision Tree Accuracy:", acc2)
print(classification_report(y_test, preds2, target_names=['Not PHA', 'PHA']))

Decision Tree Accuracy: 0.9987268271894311
              precision    recall  f1-score   support

     Not PHA       1.00      1.00      1.00    187311
         PHA       0.71      0.71      0.71       409

    accuracy                           1.00    187720
   macro avg       0.85      0.86      0.85    187720
weighted avg       1.00      1.00      1.00    187720

In [11]:
#===========================
#3.RandomForest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

model3 = RandomForestClassifier(random_state=42)
model3.fit(X_train, y_train)
preds3 = model3.predict(X_test)

acc3 = accuracy_score(y_test, preds3)
print("Random Forest Accuracy:", acc3)
print(classification_report(y_test, preds3, target_names=['Not PHA', 'PHA']))

Random Forest Accuracy: 0.998492435542297
              precision    recall  f1-score   support

     Not PHA       1.00      1.00      1.00    187311
         PHA       0.78      0.43      0.55       409

    accuracy                           1.00    187720
   macro avg       0.89      0.71      0.78    187720
weighted avg       1.00      1.00      1.00    187720

In [12]:
#====================
#4.GradientBoosting Classifier
from sklearn.ensemble import GradientBoostingClassifier

model4 = GradientBoostingClassifier(random_state=42)
model4.fit(X_train, y_train)
preds4 = model4.predict(X_test)

acc4 = accuracy_score(y_test, preds4)
print("Gradient Boosting Accuracy:", acc4)
print(classification_report(y_test, preds4, target_names=['Not PHA', 'PHA']))

Gradient Boosting Accuracy: 0.9967025356914554
              precision    recall  f1-score   support

     Not PHA       1.00      1.00      1.00    187311
         PHA       0.37      0.69      0.48       409

    accuracy                           1.00    187720
   macro avg       0.68      0.85      0.74    187720
weighted avg       1.00      1.00      1.00    187720

In [13]:
#==============================
#5.XGBoostClassifier
from xgboost import XGBClassifier

model5 = XGBClassifier(random_state=42, eval_metric='logloss')
model5.fit(X_train, y_train)
preds5 = model5.predict(X_test)

acc5 = accuracy_score(y_test, preds5)
print("XGBoost Accuracy:", acc5)
print(classification_report(y_test, preds5, target_names=['Not PHA', 'PHA']))

XGBoost Accuracy: 0.9980715959940337
              precision    recall  f1-score   support

     Not PHA       1.00      1.00      1.00    187311
         PHA       0.56      0.55      0.56       409

    accuracy                           1.00    187720
   macro avg       0.78      0.78      0.78    187720
weighted avg       1.00      1.00      1.00    187720

In [9]:
#save best model
import joblib
joblib.dump(model2, 'best_pha_model.pkl')
print("Model saved as best_pha_model.pkl")

Model saved as best_pha_model.pkl

In [31]:
joblib.dump(list(df_pha.drop(columns=['pha']).columns), 'pha_columns.pkl')
joblib.dump(sorted(data['class'].dropna().unique().tolist()), 'class_categories.pkl')

['class_categories.pkl']

REGRESSION

In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load preprocessed diameter data
df_dia = pd.read_csv('diameter_preprocessed.csv')

X = df_dia.drop(columns=['diameter'])
y = df_dia['diameter']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale features (helps Linear Regression, KNN, SVR)
scaler_dia = StandardScaler()
X_train_scaled = scaler_dia.fit_transform(X_train)
X_test_scaled = scaler_dia.transform(X_test)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

Train shape: (108967, 24)
Test shape: (27242, 24)

In [11]:
#==============================
#1.Linear Regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

model1 = LinearRegression()
model1.fit(X_train_scaled, y_train)
preds1 = model1.predict(X_test_scaled)

rmse1 = np.sqrt(mean_squared_error(y_test, preds1))
mae1 = mean_absolute_error(y_test, preds1)
r2_1 = r2_score(y_test, preds1)

print("Linear Regression")
print("RMSE:", rmse1)
print("MAE:", mae1)
print("R2 Score:", r2_1)

Linear Regression
RMSE: 8.335888410411917
MAE: 2.9095912701026028
R2 Score: 0.31119133188293746

In [12]:
#====================
#2.DecisionTree Regresssor
from sklearn.tree import DecisionTreeRegressor

model2 = DecisionTreeRegressor(random_state=42)
model2.fit(X_train, y_train)  
preds2 = model2.predict(X_test)

rmse2 = np.sqrt(mean_squared_error(y_test, preds2))
mae2 = mean_absolute_error(y_test, preds2)
r2_2 = r2_score(y_test, preds2)

print("Decision Tree Regressor")
print("RMSE:", rmse2)
print("MAE:", mae2)
print("R2 Score:", r2_2)

Decision Tree Regressor
RMSE: 4.700546701222066
MAE: 1.3894568864253725
R2 Score: 0.7809760721974616

In [13]:
#====================
#3.RandomForest Regressor
from sklearn.ensemble import RandomForestRegressor

model3 = RandomForestRegressor(random_state=42)
model3.fit(X_train, y_train)  
preds3 = model3.predict(X_test)

rmse3 = np.sqrt(mean_squared_error(y_test, preds3))
mae3 = mean_absolute_error(y_test, preds3)
r2_3 = r2_score(y_test, preds3)

print("Random Forest Regressor")
print("RMSE:", rmse3)
print("MAE:", mae3)
print("R2 Score:", r2_3)

Random Forest Regressor
RMSE: 3.829941206281797
MAE: 1.0415369829674765
R2 Score: 0.8545951028645518

In [14]:
#===========================
#4.GradientBoosting Regressor
from sklearn.ensemble import GradientBoostingRegressor

model4 = GradientBoostingRegressor(random_state=42)
model4.fit(X_train, y_train)  
preds4 = model4.predict(X_test)

rmse4 = np.sqrt(mean_squared_error(y_test, preds4))
mae4 = mean_absolute_error(y_test, preds4)
r2_4 = r2_score(y_test, preds4)

print("Gradient Boosting Regressor")
print("RMSE:", rmse4)
print("MAE:", mae4)
print("R2 Score:", r2_4)

Gradient Boosting Regressor
RMSE: 4.013295008065405
MAE: 1.1962885037793989
R2 Score: 0.8403396823329253

In [15]:
#==================
#5.XGBoost Regressor
from xgboost import XGBRegressor

model5 = XGBRegressor(random_state=42)
model5.fit(X_train, y_train) 
preds5 = model5.predict(X_test)

rmse5 = np.sqrt(mean_squared_error(y_test, preds5))
mae5 = mean_absolute_error(y_test, preds5)
r2_5 = r2_score(y_test, preds5)

print("XGBoost Regressor")
print("RMSE:", rmse5)
print("MAE:", mae5)
print("R2 Score:", r2_5)

XGBoost Regressor
RMSE: 6.847952169222634
MAE: 1.160842105014876
R2 Score: 0.5351463388461248

In [16]:
import joblib
joblib.dump(model3, 'best_diameter_model.pkl')
print("Model saved as best_diameter_model.pkl")

Model saved as best_diameter_model.pkl

In [32]:
joblib.dump(list(df_dia.drop(columns=['diameter']).columns), 'diameter_columns.pkl')

['diameter_columns.pkl']